import type { Kb } from '../kb/types.js';
import type { Manifest } from '../manifest/types.js';

import type { GeneratedProject } from './types.js';

export function generate(manifest: Manifest, _kb: Kb): GeneratedProject {
  const project: GeneratedProject = new Map();

  const solutionName = 'GabPlugin';

  project.set(`${solutionName}.sln`, generateSolutionFile(solutionName));

  project.set(`${solutionName}/${solutionName}.csproj`, generateCsprojFile(solutionName));

  project.set('README.md', generateReadme(manifest));

  return project;
}

function generateSolutionFile(solutionName: string): string {
  const projectGuid = '00000000-0000-0000-0000-000000000001';
  const solutionGuid = '00000000-0000-0000-0000-000000000000';

  return [
    '',
    'Microsoft Visual Studio Solution File, Format Version 12.00',
    '# Visual Studio Version 17',
    `Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "${solutionName}", "${solutionName}\\${solutionName}.csproj", "{${projectGuid}}"`,
    'EndProject',
    'Global',
    '\tGlobalSection(SolutionConfigurationPlatforms) = preSolution',
    '\t\tDebug|Any CPU = Debug|Any CPU',
    '\t\tRelease|Any CPU = Release|Any CPU',
    '\tEndGlobalSection',
    '\tGlobalSection(ProjectConfigurationPlatforms) = postSolution',
    `\t\t{${projectGuid}}.Debug|Any CPU.ActiveCfg = Debug|Any CPU`,
    `\t\t{${projectGuid}}.Debug|Any CPU.Build.0 = Debug|Any CPU`,
    `\t\t{${projectGuid}}.Release|Any CPU.ActiveCfg = Release|Any CPU`,
    `\t\t{${projectGuid}}.Release|Any CPU.Build.0 = Release|Any CPU`,
    '\tEndGlobalSection',
    '\tGlobalSection(SolutionProperties) = preSolution',
    '\t\tHideSolutionNode = FALSE',
    '\tEndGlobalSection',
    `\tGlobalSection(ExtensibilityGlobals) = postSolution`,
    `\t\tSolutionGuid = {${solutionGuid}}`,
    '\tEndGlobalSection',
    'EndGlobal',
    '',
  ].join('\r\n');
}

function generateCsprojFile(solutionName: string): string {
  return [
    '<Project Sdk="Microsoft.NET.Sdk">',
    '',
    '  <PropertyGroup>',
    '    <TargetFramework>net462</TargetFramework>',
    `    <RootNamespace>${solutionName}</RootNamespace>`,
    `    <AssemblyName>${solutionName}</AssemblyName>`,
    '  </PropertyGroup>',
    '',
    '</Project>',
    '',
  ].join('\n');
}

function generateReadme(manifest: Manifest): string {
  return [
    '# Generated GAB Plugin Project',
    '',
    `GAB Version: ${manifest.gabVersion}`,
    `KB Version: ${manifest.gabKbVersion}`,
    `Entities: ${manifest.entities.length === 0 ? 'none' : manifest.entities.map((e) => e.name).join(', ')}`,
    '',
    '> This project was generated by `gab generate`. Do not edit `*.Generated.cs` files.',
    '',
  ].join('\n');
}
